In [1]:
# Celda 1 — Configuracion inicial: librerias y parches de compatibilidad
#
# Este notebook (02) corre en un kernel propio, independiente del notebook 01.
# Por eso hay que volver a importar y volver a aplicar los parches: no es
# trabajo repetido en vano, es necesario porque cada notebook tiene su propia
# memoria. Esta celda es rapida, no descarga nada todavia.

import pandas as pd     # pandas: manejo de datos en tablas (DataFrames)
import requests          # requests: peticiones HTTP directas a la API de XM
import time               # time: pausas entre llamadas a la API
from pydataxm.pydataxm import ReadDB   # ReadDB: clase principal de pydataxm (catalogo de metricas)

# --- Los mismos 3 parches del notebook 01 ---
# pydataxm 0.3.17 sigue sin actualizarse para pandas 3.0, asi que estos
# parches siguen siendo necesarios en cualquier notebook que use la libreria.

_date_range_original = pd.date_range
def _date_range_parchado(*args, **kwargs):
    if kwargs.get("freq") == "M":
        kwargs["freq"] = "ME"
    return _date_range_original(*args, **kwargs)
pd.date_range = _date_range_parchado

_to_numeric_original = pd.to_numeric
def _to_numeric_parchado(*args, **kwargs):
    if kwargs.get("errors") == "ignore":
        kwargs["errors"] = "coerce"
    return _to_numeric_original(*args, **kwargs)
pd.to_numeric = _to_numeric_parchado

_to_datetime_original = pd.to_datetime
def _to_datetime_parchado(*args, **kwargs):
    if kwargs.get("errors") == "ignore":
        kwargs["errors"] = "coerce"
    return _to_datetime_original(*args, **kwargs)
pd.to_datetime = _to_datetime_parchado

print("Configuracion lista: librerias importadas y parches aplicados")

Configuracion lista: librerias importadas y parches aplicados

In [2]:
# Celda 2 — Conexion con la API de XM
# ReadDB es la clase principal de pydataxm. El catalogo (get_collections) SI
# funciona bien tal cual; el bug que encontramos solo afecta a request_data().
api = ReadDB()
print("Objeto 'api' creado correctamente")

Objeto 'api' creado correctamente

In [3]:
# Celda 3 — Cargar el dataset de precio de bolsa ya descargado
#
# No volvemos a llamar la API (ya esta guardado en data/ desde el notebook 01).
# Lo cargamos tambien aqui porque, cuando tengamos embalses y las demas
# variables, vamos a CRUZARLAS con el precio en este mismo notebook.

df_precio = pd.read_csv("../data/precio_bolsa_2019_2024.csv", parse_dates=["fecha_hora"])
print(df_precio.shape)
df_precio.head()

(52608, 2)

           fecha_hora  precio_bolsa_cop_kwh
0 2019-01-01 00:00:00              318.4231
1 2019-01-01 01:00:00              318.4231
2 2019-01-01 02:00:00              318.4231
3 2019-01-01 03:00:00              318.4231
4 2019-01-01 04:00:00              308.9231

In [4]:
# Celda 4 — Buscar en el catalogo las metricas relacionadas con embalses/hidrologia
catalogo = api.get_collections()

# Buscamos "embalse" en todas las columnas de texto del catalogo.
mascara_embalse = catalogo.apply(lambda columna: columna.astype(str).str.contains("embalse", case=False, na=False))
print("=== Resultados para 'embalse' ===")
print(catalogo[mascara_embalse.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

# XM suele separar "volumen almacenado" de "aportes hidricos" (el agua que entra).
# Buscamos tambien esta segunda palabra clave.
mascara_aporte = catalogo.apply(lambda columna: columna.astype(str).str.contains("aporte", case=False, na=False))
print("\n=== Resultados para 'aporte' ===")
print(catalogo[mascara_aporte.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

=== Resultados para 'embalse' ===
             MetricId                               MetricName   Entity  \
120          AporEner             Aportes  Energía por Sistema  Sistema
123  VoluUtilDiarEner  Volumen Útil diario Energía por Sistema  Sistema
132  CapaUtilDiarEner       Capacidad Útil Energía por Sistema  Sistema
139  VoluUtilDiarEner  Volumen Útil diario Energía por Embalse  Embalse
140  CapaUtilDiarEner       Capacidad Útil Energía por Embalse  Embalse
141          AporEner                 Aportes  Energía por Rio      Rio
150  VoluUtilDiarMasa          Volumen Útil diario por Embalse  Embalse
151          VertMasa         Vertimientos Volumen por Embalse  Embalse
154          DescMasa                    Descargas por Embalse  Embalse
155          VertEner         Vertimientos Energía por Embalse  Embalse
156          VertEner         Vertimientos Energía por Sistema  Sistema
157  CapaUtilDiarMasa       Capacidad Útil Volumen por Embalse  Embalse
158  CapaUtilDiarMasa       Capacidad Útil Volumen por Sistema  Sistema
159       VolTurbMasa            Volumen Turbinado por Embalse  Embalse
162  PorcVoluUtilDiar       Volumen Útil  diario % por Sistema  Sistema
163  PorcVoluUtilDiar       Volumen Útil  diario % por Embalse  Embalse
190   ListadoEmbalses          Listado de embalses por Sistema  Sistema

              Type MetricUnits
120  DailyEntities         kWh
123  DailyEntities         kWh
132  DailyEntities         kWh
139  DailyEntities         kWh
140  DailyEntities         kWh
141  DailyEntities         kWh
150  DailyEntities          m3
151  DailyEntities          m3
154  DailyEntities          m3
155  DailyEntities         kWh
156  DailyEntities         kWh
157  DailyEntities          m3
158  DailyEntities          m3
159  DailyEntities          m3
162  DailyEntities           %
163  DailyEntities           %
190  ListsEntities

=== Resultados para 'aporte' ===
               MetricId                                   MetricName   Entity  \
120            AporEner                 Aportes  Energía por Sistema  Sistema
131    AporEnerMediHist  Aportes Media Histórica Energía por Sistema  Sistema
141            AporEner                     Aportes  Energía por Rio      Rio
142    AporEnerMediHist      Aportes Media Histórica Energía por Rio      Rio
152          AporCaudal                       Aportes Caudal por Rio      Rio
153  AporCaudalMediHist       Aportes Media Histórica Caudal por Rio      Rio
164            PorcApor                        Aportes % por Sistema  Sistema
165            PorcApor                            Aportes % por Rio      Rio

              Type MetricUnits
120  DailyEntities         kWh
131  DailyEntities         kWh
141  DailyEntities         kWh
142  DailyEntities         kWh
152  DailyEntities        m3/s
153  DailyEntities        m3/s
164  DailyEntities           %
165  DailyEntities           %

In [5]:
# Celda 5 — Diagnostico: como viene el JSON crudo de una metrica DIARIA
#
# El precio de bolsa es HourlyEntities (24 valores por dia). Estas metricas de
# embalses son DailyEntities, asi que es probable que la estructura del JSON
# sea distinta (un solo valor por dia, no 24). Lo confirmamos antes de escribir
# la funcion de descarga, para no repetir el error de aplanado que ya tuvimos.

import json

cuerpo_peticion = {
    "MetricId": "VoluUtilDiarEner",
    "StartDate": "2024-01-01",
    "EndDate": "2024-01-03",
    "Entity": "Sistema"
}

# OJO: las metricas DailyEntities usan un endpoint distinto al de precio (/hourly).
respuesta = requests.post("https://servapibi.xm.com.co/daily", json=cuerpo_peticion)
respuesta.raise_for_status()

datos_crudos = respuesta.json()
print(json.dumps(datos_crudos["Items"][0], indent=2, ensure_ascii=False))

{
  "Date": "2024-01-01",
  "DailyEntities": [
    {
      "Id": "Sistema",
      "Value": "12161276400.00000"
    }
  ]
}

In [6]:
# Celda 6 — Funcion propia para descargar metricas DIARIAS (embalses, aportes, etc.)
#
# A diferencia del precio de bolsa (HourlyEntities, 24 valores por dia), estas
# metricas son DailyEntities: un solo valor por dia. Por eso la funcion es mas
# simple que descargar_precio_bolsa, y ademas la hacemos generica (recibe el
# MetricId como parametro) para no repetir codigo con volumen y aportes.

def descargar_metrica_diaria(metric_id, fecha_inicio, fecha_fin, entity="Sistema"):
    """
    Descarga una metrica DIARIA de la API de XM (endpoint /daily).
    Maximo 31 dias por llamado (misma restriccion que el precio horario).

    Parametros:
        metric_id: codigo de la metrica, ej. 'VoluUtilDiarEner' o 'AporEner'
        fecha_inicio, fecha_fin: strings 'YYYY-MM-DD'
        entity: nivel de agregacion, 'Sistema' por defecto (agregado nacional)

    Devuelve:
        DataFrame de pandas con columnas 'fecha' y 'valor'.
    """
    cuerpo_peticion = {
        "MetricId": metric_id,
        "StartDate": fecha_inicio,
        "EndDate": fecha_fin,
        "Entity": entity
    }

    # OJO: endpoint /daily, no /hourly como el precio de bolsa.
    respuesta = requests.post("https://servapibi.xm.com.co/daily", json=cuerpo_peticion)
    respuesta.raise_for_status()

    datos = respuesta.json()

    filas = []
    for dia in datos["Items"]:
        fecha = dia["Date"]  # ej. '2024-01-01'

        # 'DailyEntities' es una lista; para Entity='Sistema' trae un solo elemento.
        valor = float(dia["DailyEntities"][0]["Value"])  # viene como texto, lo pasamos a numero

        filas.append({"fecha": pd.Timestamp(fecha), "valor": valor})

    return pd.DataFrame(filas)


# --- Prueba con el mismo rango de antes, para comparar contra el JSON crudo ---
df_test_volumen = descargar_metrica_diaria("VoluUtilDiarEner", "2024-01-01", "2024-01-03")
print(df_test_volumen.shape)
df_test_volumen

(3, 2)

       fecha         valor
0 2024-01-01  1.216128e+10
1 2024-01-02  1.210052e+10
2 2024-01-03  1.203649e+10

In [7]:
# Celda 7 — Bucle robusto para descargar cualquier metrica DIARIA en bloques
#
# Misma logica que descargar_rango_robusto (precio horario), pero generica:
# recibe el metric_id como parametro, para reutilizarla con volumen, aportes,
# o cualquier otra metrica diaria que necesitemos mas adelante.

def descargar_rango_diario_robusto(metric_id, fecha_inicio_total, fecha_fin_total,
                                     dias_por_bloque=30, max_reintentos=3, entity="Sistema"):
    """
    Descarga una metrica diaria para un rango largo, en bloques, con reintentos.

    Devuelve una tupla: (df_completo, bloques_fallidos)
    """
    fecha_actual = pd.Timestamp(fecha_inicio_total)
    fecha_limite = pd.Timestamp(fecha_fin_total)

    bloques_descargados = []
    bloques_fallidos = []
    numero_bloque = 1

    while fecha_actual <= fecha_limite:
        fin_de_bloque = min(fecha_actual + pd.Timedelta(days=dias_por_bloque - 1), fecha_limite)
        inicio_str = fecha_actual.strftime("%Y-%m-%d")
        fin_str = fin_de_bloque.strftime("%Y-%m-%d")

        exito = False
        for intento in range(1, max_reintentos + 1):
            try:
                df_bloque = descargar_metrica_diaria(metric_id, inicio_str, fin_str, entity)
                bloques_descargados.append(df_bloque)
                print(f"[{metric_id}] Bloque {numero_bloque} OK: {inicio_str} a {fin_str} ({len(df_bloque)} filas)")
                exito = True
                break
            except Exception as error:
                print(f"  [{metric_id}] Bloque {numero_bloque} intento {intento} fallo: {error}")
                time.sleep(intento * 3)

        if not exito:
            bloques_fallidos.append((inicio_str, fin_str))
            print(f"  [{metric_id}] Bloque {numero_bloque} DESCARTADO tras {max_reintentos} intentos")

        fecha_actual = fin_de_bloque + pd.Timedelta(days=1)
        numero_bloque += 1
        time.sleep(1)

    if bloques_descargados:
        df_completo = pd.concat(bloques_descargados, ignore_index=True)
        df_completo = df_completo.sort_values("fecha").drop_duplicates("fecha").reset_index(drop=True)
    else:
        df_completo = pd.DataFrame()

    return df_completo, bloques_fallidos

print("Funcion 'descargar_rango_diario_robusto' definida correctamente")

Funcion 'descargar_rango_diario_robusto' definida correctamente

In [8]:
# Celda 8 — Prueba corta con AMBAS metricas (3 meses), antes de ir a 6 años

df_prueba_volumen, fallos_v = descargar_rango_diario_robusto("VoluUtilDiarEner", "2024-01-01", "2024-03-31")
print("\nVolumen ->", df_prueba_volumen.shape, "| fallidos:", len(fallos_v))

df_prueba_aportes, fallos_a = descargar_rango_diario_robusto("AporEner", "2024-01-01", "2024-03-31")
print("Aportes  ->", df_prueba_aportes.shape, "| fallidos:", len(fallos_a))

[VoluUtilDiarEner] Bloque 1 OK: 2024-01-01 a 2024-01-30 (30 filas)
[VoluUtilDiarEner] Bloque 2 OK: 2024-01-31 a 2024-02-29 (30 filas)
[VoluUtilDiarEner] Bloque 3 OK: 2024-03-01 a 2024-03-30 (30 filas)
[VoluUtilDiarEner] Bloque 4 OK: 2024-03-31 a 2024-03-31 (1 filas)

Volumen -> (91, 2) | fallidos: 0
[AporEner] Bloque 1 OK: 2024-01-01 a 2024-01-30 (30 filas)
[AporEner] Bloque 2 OK: 2024-01-31 a 2024-02-29 (30 filas)
[AporEner] Bloque 3 OK: 2024-03-01 a 2024-03-30 (30 filas)
[AporEner] Bloque 4 OK: 2024-03-31 a 2024-03-31 (1 filas)
Aportes  -> (91, 2) | fallidos: 0

In [9]:
# Celda 9 — Mini-prueba: confirmar que existen datos de embalses desde 2019
df_test_vol_2019 = descargar_metrica_diaria("VoluUtilDiarEner", "2019-01-01", "2019-01-05")
print("Volumen 2019 ->", df_test_vol_2019.shape)
print(df_test_vol_2019)

df_test_apor_2019 = descargar_metrica_diaria("AporEner", "2019-01-01", "2019-01-05")
print("\nAportes 2019 ->", df_test_apor_2019.shape)
print(df_test_apor_2019)

Volumen 2019 -> (5, 2)
       fecha         valor
0 2019-01-01  1.210678e+10
1 2019-01-02  1.203963e+10
2 2019-01-03  1.195639e+10
3 2019-01-04  1.187703e+10
4 2019-01-05  1.180290e+10

Aportes 2019 -> (5, 2)
       fecha       valor
0 2019-01-01  63035900.0
1 2019-01-02  60901300.0
2 2019-01-03  64058000.0
3 2019-01-04  62531300.0
4 2019-01-05  62769100.0

In [10]:
# Celda 10 — Descarga COMPLETA 2019-2024 de volumen util y aportes, y guardado en disco
#
# Dos descargas independientes, cada una en su propio archivo .csv dentro de data/.
# Reutilizamos la funcion generica descargar_rango_diario_robusto que ya validamos.

# --- Volumen util diario de embalses (energia almacenada) ---
df_volumen, fallos_volumen = descargar_rango_diario_robusto("VoluUtilDiarEner", "2019-01-01", "2024-12-31")

print("\n===== RESUMEN VOLUMEN =====")
print("Total de filas:", df_volumen.shape[0])
print("Rango de fechas:", df_volumen["fecha"].min(), "a", df_volumen["fecha"].max())
print("Bloques fallidos:", len(fallos_volumen))

df_volumen.to_csv("../data/volumen_util_embalses_2019_2024.csv", index=False)
print("Guardado en: ../data/volumen_util_embalses_2019_2024.csv")

# --- Aportes hidricos diarios (energia equivalente que entra a los embalses) ---
df_aportes, fallos_aportes = descargar_rango_diario_robusto("AporEner", "2019-01-01", "2024-12-31")

print("\n===== RESUMEN APORTES =====")
print("Total de filas:", df_aportes.shape[0])
print("Rango de fechas:", df_aportes["fecha"].min(), "a", df_aportes["fecha"].max())
print("Bloques fallidos:", len(fallos_aportes))

df_aportes.to_csv("../data/aportes_hidricos_2019_2024.csv", index=False)
print("Guardado en: ../data/aportes_hidricos_2019_2024.csv")

[VoluUtilDiarEner] Bloque 1 OK: 2019-01-01 a 2019-01-30 (30 filas)
[VoluUtilDiarEner] Bloque 2 OK: 2019-01-31 a 2019-03-01 (30 filas)
[VoluUtilDiarEner] Bloque 3 OK: 2019-03-02 a 2019-03-31 (30 filas)
[VoluUtilDiarEner] Bloque 4 OK: 2019-04-01 a 2019-04-30 (30 filas)
[VoluUtilDiarEner] Bloque 5 OK: 2019-05-01 a 2019-05-30 (30 filas)
[VoluUtilDiarEner] Bloque 6 OK: 2019-05-31 a 2019-06-29 (30 filas)
[VoluUtilDiarEner] Bloque 7 OK: 2019-06-30 a 2019-07-29 (30 filas)
[VoluUtilDiarEner] Bloque 8 OK: 2019-07-30 a 2019-08-28 (30 filas)
[VoluUtilDiarEner] Bloque 9 OK: 2019-08-29 a 2019-09-27 (30 filas)
[VoluUtilDiarEner] Bloque 10 OK: 2019-09-28 a 2019-10-27 (30 filas)
[VoluUtilDiarEner] Bloque 11 OK: 2019-10-28 a 2019-11-26 (30 filas)
[VoluUtilDiarEner] Bloque 12 OK: 2019-11-27 a 2019-12-26 (30 filas)
[VoluUtilDiarEner] Bloque 13 OK: 2019-12-27 a 2020-01-25 (30 filas)
[VoluUtilDiarEner] Bloque 14 OK: 2020-01-26 a 2020-02-24 (30 filas)
[VoluUtilDiarEner] Bloque 15 OK: 2020-02-25 a 2020-03-25 (30 filas)
[VoluUtilDiarEner] Bloque 16 OK: 2020-03-26 a 2020-04-24 (30 filas)
[VoluUtilDiarEner] Bloque 17 OK: 2020-04-25 a 2020-05-24 (30 filas)
[VoluUtilDiarEner] Bloque 18 OK: 2020-05-25 a 2020-06-23 (30 filas)
[VoluUtilDiarEner] Bloque 19 OK: 2020-06-24 a 2020-07-23 (30 filas)
[VoluUtilDiarEner] Bloque 20 OK: 2020-07-24 a 2020-08-22 (30 filas)
[VoluUtilDiarEner] Bloque 21 OK: 2020-08-23 a 2020-09-21 (30 filas)
[VoluUtilDiarEner] Bloque 22 OK: 2020-09-22 a 2020-10-21 (30 filas)
[VoluUtilDiarEner] Bloque 23 OK: 2020-10-22 a 2020-11-20 (30 filas)
[VoluUtilDiarEner] Bloque 24 OK: 2020-11-21 a 2020-12-20 (30 filas)
[VoluUtilDiarEner] Bloque 25 OK: 2020-12-21 a 2021-01-19 (30 filas)
[VoluUtilDiarEner] Bloque 26 OK: 2021-01-20 a 2021-02-18 (30 filas)
[VoluUtilDiarEner] Bloque 27 OK: 2021-02-19 a 2021-03-20 (30 filas)
[VoluUtilDiarEner] Bloque 28 OK: 2021-03-21 a 2021-04-19 (30 filas)
[VoluUtilDiarEner] Bloque 29 OK: 2021-04-20 a 2021-05-19 (30 filas)
[VoluUtilDiarEner] Bloque 30 OK: 2021-05-20 a 2021-06-18 (30 filas)
[VoluUtilDiarEner] Bloque 31 OK: 2021-06-19 a 2021-07-18 (30 filas)
[VoluUtilDiarEner] Bloque 32 OK: 2021-07-19 a 2021-08-17 (30 filas)
[VoluUtilDiarEner] Bloque 33 OK: 2021-08-18 a 2021-09-16 (30 filas)
[VoluUtilDiarEner] Bloque 34 OK: 2021-09-17 a 2021-10-16 (30 filas)
[VoluUtilDiarEner] Bloque 35 OK: 2021-10-17 a 2021-11-15 (30 filas)
[VoluUtilDiarEner] Bloque 36 OK: 2021-11-16 a 2021-12-15 (30 filas)
[VoluUtilDiarEner] Bloque 37 OK: 2021-12-16 a 2022-01-14 (30 filas)
[VoluUtilDiarEner] Bloque 38 OK: 2022-01-15 a 2022-02-13 (30 filas)
[VoluUtilDiarEner] Bloque 39 OK: 2022-02-14 a 2022-03-15 (30 filas)
[VoluUtilDiarEner] Bloque 40 OK: 2022-03-16 a 2022-04-14 (30 filas)
[VoluUtilDiarEner] Bloque 41 OK: 2022-04-15 a 2022-05-14 (30 filas)
[VoluUtilDiarEner] Bloque 42 OK: 2022-05-15 a 2022-06-13 (30 filas)
[VoluUtilDiarEner] Bloque 43 OK: 2022-06-14 a 2022-07-13 (30 filas)
[VoluUtilDiarEner] Bloque 44 OK: 2022-07-14 a 2022-08-12 (30 filas)
[VoluUtilDiarEner] Bloque 45 OK: 2022-08-13 a 2022-09-11 (30 filas)
[VoluUtilDiarEner] Bloque 46 OK: 2022-09-12 a 2022-10-11 (30 filas)
[VoluUtilDiarEner] Bloque 47 OK: 2022-10-12 a 2022-11-10 (30 filas)
[VoluUtilDiarEner] Bloque 48 OK: 2022-11-11 a 2022-12-10 (30 filas)
[VoluUtilDiarEner] Bloque 49 OK: 2022-12-11 a 2023-01-09 (30 filas)
[VoluUtilDiarEner] Bloque 50 OK: 2023-01-10 a 2023-02-08 (30 filas)
[VoluUtilDiarEner] Bloque 51 OK: 2023-02-09 a 2023-03-10 (30 filas)
[VoluUtilDiarEner] Bloque 52 OK: 2023-03-11 a 2023-04-09 (30 filas)
[VoluUtilDiarEner] Bloque 53 OK: 2023-04-10 a 2023-05-09 (30 filas)
[VoluUtilDiarEner] Bloque 54 OK: 2023-05-10 a 2023-06-08 (30 filas)
[VoluUtilDiarEner] Bloque 55 OK: 2023-06-09 a 2023-07-08 (30 filas)
[VoluUtilDiarEner] Bloque 56 OK: 2023-07-09 a 2023-08-07 (30 filas)
[VoluUtilDiarEner] Bloque 57 OK: 2023-08-08 a 2023-09-06 (30 filas)
[VoluUtilDiarEner] Bloque 58 OK: 2023-09-07 a 2023-10-06 (30 filas)
[VoluUtilDiarEner] Bloque 59 OK: 2023-10-07 a 2023-11-05 (30 filas)
[VoluUtilDiarEner] Bloque 60 OK: 2023-11-06 a 2023-12-05 (30 filas)
[VoluUtilDiarEner] Bloque 61 OK: 2023-12-06 a 2024-01-04 (30 filas)
[VoluUtilDiarEner] Bloque 62 OK: 2024-01-05 a 2024-02-03 (30 filas)
[VoluUtilDiarEner] Bloque 63 OK: 2024-02-04 a 2024-03-04 (30 filas)
[VoluUtilDiarEner] Bloque 64 OK: 2024-03-05 a 2024-04-03 (30 filas)
[VoluUtilDiarEner] Bloque 65 OK: 2024-04-04 a 2024-05-03 (30 filas)
[VoluUtilDiarEner] Bloque 66 OK: 2024-05-04 a 2024-06-02 (30 filas)
[VoluUtilDiarEner] Bloque 67 OK: 2024-06-03 a 2024-07-02 (30 filas)
[VoluUtilDiarEner] Bloque 68 OK: 2024-07-03 a 2024-08-01 (30 filas)
[VoluUtilDiarEner] Bloque 69 OK: 2024-08-02 a 2024-08-31 (30 filas)
[VoluUtilDiarEner] Bloque 70 OK: 2024-09-01 a 2024-09-30 (30 filas)
[VoluUtilDiarEner] Bloque 71 OK: 2024-10-01 a 2024-10-30 (30 filas)
[VoluUtilDiarEner] Bloque 72 OK: 2024-10-31 a 2024-11-29 (30 filas)
[VoluUtilDiarEner] Bloque 73 OK: 2024-11-30 a 2024-12-29 (30 filas)
[VoluUtilDiarEner] Bloque 74 OK: 2024-12-30 a 2024-12-31 (2 filas)

===== RESUMEN VOLUMEN =====
Total de filas: 2192
Rango de fechas: 2019-01-01 00:00:00 a 2024-12-31 00:00:00
Bloques fallidos: 0
Guardado en: ../data/volumen_util_embalses_2019_2024.csv
[AporEner] Bloque 1 OK: 2019-01-01 a 2019-01-30 (30 filas)
[AporEner] Bloque 2 OK: 2019-01-31 a 2019-03-01 (30 filas)
[AporEner] Bloque 3 OK: 2019-03-02 a 2019-03-31 (30 filas)
[AporEner] Bloque 4 OK: 2019-04-01 a 2019-04-30 (30 filas)
[AporEner] Bloque 5 OK: 2019-05-01 a 2019-05-30 (30 filas)
[AporEner] Bloque 6 OK: 2019-05-31 a 2019-06-29 (30 filas)
[AporEner] Bloque 7 OK: 2019-06-30 a 2019-07-29 (30 filas)
[AporEner] Bloque 8 OK: 2019-07-30 a 2019-08-28 (30 filas)
[AporEner] Bloque 9 OK: 2019-08-29 a 2019-09-27 (30 filas)
[AporEner] Bloque 10 OK: 2019-09-28 a 2019-10-27 (30 filas)
[AporEner] Bloque 11 OK: 2019-10-28 a 2019-11-26 (30 filas)
[AporEner] Bloque 12 OK: 2019-11-27 a 2019-12-26 (30 filas)
[AporEner] Bloque 13 OK: 2019-12-27 a 2020-01-25 (30 filas)
[AporEner] Bloque 14 OK: 2020-01-26 a 2020-02-24 (30 filas)
[AporEner] Bloque 15 OK: 2020-02-25 a 2020-03-25 (30 filas)
[AporEner] Bloque 16 OK: 2020-03-26 a 2020-04-24 (30 filas)
[AporEner] Bloque 17 OK: 2020-04-25 a 2020-05-24 (30 filas)
[AporEner] Bloque 18 OK: 2020-05-25 a 2020-06-23 (30 filas)
[AporEner] Bloque 19 OK: 2020-06-24 a 2020-07-23 (30 filas)
[AporEner] Bloque 20 OK: 2020-07-24 a 2020-08-22 (30 filas)
[AporEner] Bloque 21 OK: 2020-08-23 a 2020-09-21 (30 filas)
[AporEner] Bloque 22 OK: 2020-09-22 a 2020-10-21 (30 filas)
[AporEner] Bloque 23 OK: 2020-10-22 a 2020-11-20 (30 filas)
[AporEner] Bloque 24 OK: 2020-11-21 a 2020-12-20 (30 filas)
[AporEner] Bloque 25 OK: 2020-12-21 a 2021-01-19 (30 filas)
[AporEner] Bloque 26 OK: 2021-01-20 a 2021-02-18 (30 filas)
[AporEner] Bloque 27 OK: 2021-02-19 a 2021-03-20 (30 filas)
[AporEner] Bloque 28 OK: 2021-03-21 a 2021-04-19 (30 filas)
[AporEner] Bloque 29 OK: 2021-04-20 a 2021-05-19 (30 filas)
[AporEner] Bloque 30 OK: 2021-05-20 a 2021-06-18 (30 filas)
[AporEner] Bloque 31 OK: 2021-06-19 a 2021-07-18 (30 filas)
[AporEner] Bloque 32 OK: 2021-07-19 a 2021-08-17 (30 filas)
[AporEner] Bloque 33 OK: 2021-08-18 a 2021-09-16 (30 filas)
[AporEner] Bloque 34 OK: 2021-09-17 a 2021-10-16 (30 filas)
[AporEner] Bloque 35 OK: 2021-10-17 a 2021-11-15 (30 filas)
[AporEner] Bloque 36 OK: 2021-11-16 a 2021-12-15 (30 filas)
[AporEner] Bloque 37 OK: 2021-12-16 a 2022-01-14 (30 filas)
[AporEner] Bloque 38 OK: 2022-01-15 a 2022-02-13 (30 filas)
[AporEner] Bloque 39 OK: 2022-02-14 a 2022-03-15 (30 filas)
[AporEner] Bloque 40 OK: 2022-03-16 a 2022-04-14 (30 filas)
[AporEner] Bloque 41 OK: 2022-04-15 a 2022-05-14 (30 filas)
[AporEner] Bloque 42 OK: 2022-05-15 a 2022-06-13 (30 filas)
[AporEner] Bloque 43 OK: 2022-06-14 a 2022-07-13 (30 filas)
[AporEner] Bloque 44 OK: 2022-07-14 a 2022-08-12 (30 filas)
[AporEner] Bloque 45 OK: 2022-08-13 a 2022-09-11 (30 filas)
[AporEner] Bloque 46 OK: 2022-09-12 a 2022-10-11 (30 filas)
[AporEner] Bloque 47 OK: 2022-10-12 a 2022-11-10 (30 filas)
[AporEner] Bloque 48 OK: 2022-11-11 a 2022-12-10 (30 filas)
[AporEner] Bloque 49 OK: 2022-12-11 a 2023-01-09 (30 filas)
[AporEner] Bloque 50 OK: 2023-01-10 a 2023-02-08 (30 filas)
[AporEner] Bloque 51 OK: 2023-02-09 a 2023-03-10 (30 filas)
[AporEner] Bloque 52 OK: 2023-03-11 a 2023-04-09 (30 filas)
[AporEner] Bloque 53 OK: 2023-04-10 a 2023-05-09 (30 filas)
[AporEner] Bloque 54 OK: 2023-05-10 a 2023-06-08 (30 filas)
[AporEner] Bloque 55 OK: 2023-06-09 a 2023-07-08 (30 filas)
[AporEner] Bloque 56 OK: 2023-07-09 a 2023-08-07 (30 filas)
[AporEner] Bloque 57 OK: 2023-08-08 a 2023-09-06 (30 filas)
[AporEner] Bloque 58 OK: 2023-09-07 a 2023-10-06 (30 filas)
[AporEner] Bloque 59 OK: 2023-10-07 a 2023-11-05 (30 filas)
[AporEner] Bloque 60 OK: 2023-11-06 a 2023-12-05 (30 filas)
[AporEner] Bloque 61 OK: 2023-12-06 a 2024-01-04 (30 filas)
[AporEner] Bloque 62 OK: 2024-01-05 a 2024-02-03 (30 filas)
[AporEner] Bloque 63 OK: 2024-02-04 a 2024-03-04 (30 filas)
[AporEner] Bloque 64 OK: 2024-03-05 a 2024-04-03 (30 filas)
[AporEner] Bloque 65 OK: 2024-04-04 a 2024-05-03 (30 filas)
[AporEner] Bloque 66 OK: 2024-05-04 a 2024-06-02 (30 filas)
[AporEner] Bloque 67 OK: 2024-06-03 a 2024-07-02 (30 filas)
[AporEner] Bloque 68 OK: 2024-07-03 a 2024-08-01 (30 filas)
[AporEner] Bloque 69 OK: 2024-08-02 a 2024-08-31 (30 filas)
[AporEner] Bloque 70 OK: 2024-09-01 a 2024-09-30 (30 filas)
[AporEner] Bloque 71 OK: 2024-10-01 a 2024-10-30 (30 filas)
[AporEner] Bloque 72 OK: 2024-10-31 a 2024-11-29 (30 filas)
[AporEner] Bloque 73 OK: 2024-11-30 a 2024-12-29 (30 filas)
[AporEner] Bloque 74 OK: 2024-12-30 a 2024-12-31 (2 filas)

===== RESUMEN APORTES =====
Total de filas: 2192
Rango de fechas: 2019-01-01 00:00:00 a 2024-12-31 00:00:00
Bloques fallidos: 0
Guardado en: ../data/aportes_hidricos_2019_2024.csv

In [11]:
# Celda 11 — Descargar SOLO 2025 y extender los archivos ya guardados
#
# Ya tenemos 2019-2024 completo y guardado. En vez de repetir esa descarga,
# solo pedimos el pedazo que falta (2025) y lo concatenamos con lo que ya existe.

# --- Volumen: descargar solo 2025 ---
df_volumen_2025, fallos_v25 = descargar_rango_diario_robusto("VoluUtilDiarEner", "2025-01-01", "2025-12-31")
print("Volumen 2025 ->", df_volumen_2025.shape, "| fallidos:", len(fallos_v25))

# --- Aportes: descargar solo 2025 ---
df_aportes_2025, fallos_a25 = descargar_rango_diario_robusto("AporEner", "2025-01-01", "2025-12-31")
print("Aportes 2025 ->", df_aportes_2025.shape, "| fallidos:", len(fallos_a25))

[VoluUtilDiarEner] Bloque 1 OK: 2025-01-01 a 2025-01-30 (30 filas)
[VoluUtilDiarEner] Bloque 2 OK: 2025-01-31 a 2025-03-01 (30 filas)
[VoluUtilDiarEner] Bloque 3 OK: 2025-03-02 a 2025-03-31 (30 filas)
[VoluUtilDiarEner] Bloque 4 OK: 2025-04-01 a 2025-04-30 (30 filas)
[VoluUtilDiarEner] Bloque 5 OK: 2025-05-01 a 2025-05-30 (30 filas)
[VoluUtilDiarEner] Bloque 6 OK: 2025-05-31 a 2025-06-29 (30 filas)
[VoluUtilDiarEner] Bloque 7 OK: 2025-06-30 a 2025-07-29 (30 filas)
[VoluUtilDiarEner] Bloque 8 OK: 2025-07-30 a 2025-08-28 (30 filas)
[VoluUtilDiarEner] Bloque 9 OK: 2025-08-29 a 2025-09-27 (30 filas)
[VoluUtilDiarEner] Bloque 10 OK: 2025-09-28 a 2025-10-27 (30 filas)
[VoluUtilDiarEner] Bloque 11 OK: 2025-10-28 a 2025-11-26 (30 filas)
[VoluUtilDiarEner] Bloque 12 OK: 2025-11-27 a 2025-12-26 (30 filas)
[VoluUtilDiarEner] Bloque 13 OK: 2025-12-27 a 2025-12-31 (5 filas)
Volumen 2025 -> (365, 2) | fallidos: 0
[AporEner] Bloque 1 OK: 2025-01-01 a 2025-01-30 (30 filas)
[AporEner] Bloque 2 OK: 2025-01-31 a 2025-03-01 (30 filas)
[AporEner] Bloque 3 OK: 2025-03-02 a 2025-03-31 (30 filas)
[AporEner] Bloque 4 OK: 2025-04-01 a 2025-04-30 (30 filas)
[AporEner] Bloque 5 OK: 2025-05-01 a 2025-05-30 (30 filas)
[AporEner] Bloque 6 OK: 2025-05-31 a 2025-06-29 (30 filas)
[AporEner] Bloque 7 OK: 2025-06-30 a 2025-07-29 (30 filas)
[AporEner] Bloque 8 OK: 2025-07-30 a 2025-08-28 (30 filas)
[AporEner] Bloque 9 OK: 2025-08-29 a 2025-09-27 (30 filas)
[AporEner] Bloque 10 OK: 2025-09-28 a 2025-10-27 (30 filas)
[AporEner] Bloque 11 OK: 2025-10-28 a 2025-11-26 (30 filas)
[AporEner] Bloque 12 OK: 2025-11-27 a 2025-12-26 (30 filas)
[AporEner] Bloque 13 OK: 2025-12-27 a 2025-12-31 (5 filas)
Aportes 2025 -> (365, 2) | fallidos: 0

In [12]:
# Celda 12 — Unir 2025 con lo ya guardado (2019-2024) y volver a guardar

# Cargamos lo que ya teniamos en disco
df_volumen_2019_2024 = pd.read_csv("../data/volumen_util_embalses_2019_2024.csv", parse_dates=["fecha"])
df_aportes_2019_2024 = pd.read_csv("../data/aportes_hidricos_2019_2024.csv", parse_dates=["fecha"])

# Concatenamos con el pedazo nuevo de 2025, ordenamos y quitamos posibles duplicados
df_volumen_completo = pd.concat([df_volumen_2019_2024, df_volumen_2025], ignore_index=True)
df_volumen_completo = df_volumen_completo.sort_values("fecha").drop_duplicates("fecha").reset_index(drop=True)

df_aportes_completo = pd.concat([df_aportes_2019_2024, df_aportes_2025], ignore_index=True)
df_aportes_completo = df_aportes_completo.sort_values("fecha").drop_duplicates("fecha").reset_index(drop=True)

print("Volumen 2019-2025 ->", df_volumen_completo.shape)
print("Aportes 2019-2025 ->", df_aportes_completo.shape)

# Guardamos con nombres actualizados que reflejan el nuevo rango
df_volumen_completo.to_csv("../data/volumen_util_embalses_2019_2025.csv", index=False)
df_aportes_completo.to_csv("../data/aportes_hidricos_2019_2025.csv", index=False)
print("\nGuardado: volumen_util_embalses_2019_2025.csv y aportes_hidricos_2019_2025.csv")

Volumen 2019-2025 -> (2557, 2)
Aportes 2019-2025 -> (2557, 2)

Guardado: volumen_util_embalses_2019_2025.csv y aportes_hidricos_2019_2025.csv

In [13]:
# Celda 13 — Traer la funcion de descarga horaria (definida en el notebook 01)
# para poder extender tambien el precio de bolsa a 2025 desde aqui.

def descargar_precio_bolsa(fecha_inicio, fecha_fin):
    """Descarga el Precio de Bolsa Nacional (COP/kWh) para un rango de fechas."""
    cuerpo_peticion = {
        "MetricId": "PrecBolsNaci",
        "StartDate": fecha_inicio,
        "EndDate": fecha_fin,
        "Entity": "Sistema"
    }
    respuesta = requests.post("https://servapibi.xm.com.co/hourly", json=cuerpo_peticion)
    respuesta.raise_for_status()
    datos = respuesta.json()

    filas = []
    for dia in datos["Items"]:
        fecha = dia["Date"]
        valores_del_dia = dia["HourlyEntities"][0]["Values"]
        for hora in range(1, 25):
            clave_hora = f"Hour{hora:02d}"
            precio = float(valores_del_dia[clave_hora])
            fecha_hora = pd.Timestamp(fecha) + pd.Timedelta(hours=hora - 1)
            filas.append({"fecha_hora": fecha_hora, "precio_bolsa_cop_kwh": precio})
    return pd.DataFrame(filas)


def descargar_rango_robusto(fecha_inicio_total, fecha_fin_total, dias_por_bloque=30, max_reintentos=3):
    """Descarga precio de bolsa en bloques, con reintentos."""
    fecha_actual = pd.Timestamp(fecha_inicio_total)
    fecha_limite = pd.Timestamp(fecha_fin_total)
    bloques_descargados = []
    bloques_fallidos = []
    numero_bloque = 1

    while fecha_actual <= fecha_limite:
        fin_de_bloque = min(fecha_actual + pd.Timedelta(days=dias_por_bloque - 1), fecha_limite)
        inicio_str = fecha_actual.strftime("%Y-%m-%d")
        fin_str = fin_de_bloque.strftime("%Y-%m-%d")

        exito = False
        for intento in range(1, max_reintentos + 1):
            try:
                df_bloque = descargar_precio_bolsa(inicio_str, fin_str)
                bloques_descargados.append(df_bloque)
                print(f"Bloque {numero_bloque} OK: {inicio_str} a {fin_str} ({len(df_bloque)} filas)")
                exito = True
                break
            except Exception as error:
                print(f"  Bloque {numero_bloque} intento {intento} fallo: {error}")
                time.sleep(intento * 3)

        if not exito:
            bloques_fallidos.append((inicio_str, fin_str))
        fecha_actual = fin_de_bloque + pd.Timedelta(days=1)
        numero_bloque += 1
        time.sleep(1)

    if bloques_descargados:
        df_completo = pd.concat(bloques_descargados, ignore_index=True)
        df_completo = df_completo.sort_values("fecha_hora").drop_duplicates("fecha_hora").reset_index(drop=True)
    else:
        df_completo = pd.DataFrame()
    return df_completo, bloques_fallidos

print("Funciones de precio horario listas")

Funciones de precio horario listas

In [14]:
# Celda 14 — Descargar SOLO 2025 del precio y extender el archivo ya guardado
df_precio_2025, fallos_p25 = descargar_rango_robusto("2025-01-01", "2025-12-31")
print("Precio 2025 ->", df_precio_2025.shape, "| fallidos:", len(fallos_p25))

# Unimos con lo que ya teniamos (2019-2024, del notebook 01)
df_precio_2019_2024 = pd.read_csv("../data/precio_bolsa_2019_2024.csv", parse_dates=["fecha_hora"])
df_precio_completo = pd.concat([df_precio_2019_2024, df_precio_2025], ignore_index=True)
df_precio_completo = df_precio_completo.sort_values("fecha_hora").drop_duplicates("fecha_hora").reset_index(drop=True)

print("Precio 2019-2025 ->", df_precio_completo.shape)

df_precio_completo.to_csv("../data/precio_bolsa_2019_2025.csv", index=False)
print("Guardado: precio_bolsa_2019_2025.csv")

Bloque 1 OK: 2025-01-01 a 2025-01-30 (720 filas)
Bloque 2 OK: 2025-01-31 a 2025-03-01 (720 filas)
Bloque 3 OK: 2025-03-02 a 2025-03-31 (720 filas)
Bloque 4 OK: 2025-04-01 a 2025-04-30 (720 filas)
Bloque 5 OK: 2025-05-01 a 2025-05-30 (720 filas)
Bloque 6 OK: 2025-05-31 a 2025-06-29 (720 filas)
Bloque 7 OK: 2025-06-30 a 2025-07-29 (720 filas)
Bloque 8 OK: 2025-07-30 a 2025-08-28 (720 filas)
Bloque 9 OK: 2025-08-29 a 2025-09-27 (720 filas)
Bloque 10 OK: 2025-09-28 a 2025-10-27 (720 filas)
Bloque 11 OK: 2025-10-28 a 2025-11-26 (720 filas)
Bloque 12 OK: 2025-11-27 a 2025-12-26 (720 filas)
Bloque 13 OK: 2025-12-27 a 2025-12-31 (120 filas)
Precio 2025 -> (8760, 2) | fallidos: 0
Precio 2019-2025 -> (61368, 2)
Guardado: precio_bolsa_2019_2025.csv

In [15]:
# Celda 15 — Eliminar los archivos viejos (2019-2024), ya reemplazados por 2019-2025

import os  # os: para verificar/eliminar archivos del sistema

archivos_viejos = [
    "../data/precio_bolsa_2019_2024.csv",
    "../data/volumen_util_embalses_2019_2024.csv",
    "../data/aportes_hidricos_2019_2024.csv",
]

for archivo in archivos_viejos:
    if os.path.exists(archivo):
        os.remove(archivo)
        print(f"Eliminado: {archivo}")
    else:
        print(f"No encontrado (ya no existia): {archivo}")

# Confirmamos que ahora solo quedan los archivos 2019-2025 en data/
print("\nContenido actual de data/:")
print([f for f in os.listdir("../data") if f.endswith(".csv")])

Eliminado: ../data/precio_bolsa_2019_2024.csv
Eliminado: ../data/volumen_util_embalses_2019_2024.csv
Eliminado: ../data/aportes_hidricos_2019_2024.csv

Contenido actual de data/:
['aportes_hidricos_2019_2025.csv', 'precio_bolsa_2019_2025.csv', 'volumen_util_embalses_2019_2025.csv']

In [16]:
# Celda 16 — Buscar en el catalogo las metricas de demanda y generacion
#
# Reutilizamos la variable 'catalogo' que ya esta en memoria (la trajimos en la
# celda 4 de este mismo notebook, para buscar "embalse"). No hace falta volver
# a llamar get_collections().

mascara_demanda = catalogo.apply(lambda columna: columna.astype(str).str.contains("demanda", case=False, na=False))
print("=== Resultados para 'demanda' ===")
print(catalogo[mascara_demanda.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

# Buscamos "generaci" (sin acento y truncado) para capturar tanto "generación" como "Generacion"
mascara_generacion = catalogo.apply(lambda columna: columna.astype(str).str.contains("generaci", case=False, na=False))
print("\n=== Resultados para 'generación' ===")
print(catalogo[mascara_generacion.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

=== Resultados para 'demanda' ===
            MetricId                                         MetricName  \
0           DemaReal                           Demanda Real por Sistema
1           DemaReal                            Demanda Real por Agente
3           DemaCome                      Demanda Comercial por Sistema
6       PrecBolsNaci                  Precio Bolsa Nacional por Sistema
12          DemaCome                       Demanda Comercial por Agente
..               ...                                                ...
143    DDVContratada                         DDV Contratada por Recurso
144       DemaMaxPot             Demanda Máxima de Potencia por Sistema
182   EscDemUPMEAlto  Demanda de Energia Proyectada UPME Escenario A...
183  EscDemUPMEMedio  Demanda de Energia Proyectada UPME Escenario M...
184   EscDemUPMEBajo  Demanda de Energia Proyectada UPME Escenario B...

      Entity             Type MetricUnits
0    Sistema   HourlyEntities         kWh
1     Agente   HourlyEntities         kWh
3    Sistema   HourlyEntities         kWh
6    Sistema   HourlyEntities     COP/kWh
12    Agente   HourlyEntities         kWh
..       ...              ...         ...
143  Recurso    DailyEntities         kWh
144  Sistema    DailyEntities          kW
182  Sistema  MonthlyEntities         kWh
183  Sistema  MonthlyEntities         kWh
184  Sistema  MonthlyEntities         kWh

[61 rows x 5 columns]

=== Resultados para 'generación' ===
                  MetricId                                         MetricName  \
4                     Gene                             Generación por Sistema
5                 GeneIdea                       Generación Ideal por Sistema
8      ConsCombustibleMBTU               Consumo Combustible MBTU por Recurso
9      ConsCombustibleMBTU                           Consumo Combustible MBTU
10                    Gene                             Generación por Recurso
11           IndRecMargina              Indicador Recurso Margina por Recurso
13            PrecOferDesp           Precio de Oferta de Despacho por Recurso
21                GeneIdea                       Generación Ideal por Recurso
22           ConsCombAprox  Consumo Combustible Aproximado para el Factor ...
23            EmisionesCO2                   Emisiones de CO2 por RecursoComb
24            EmisionesCH4                   Emisiones de CH4 por RecursoComb
25            EmisionesN2O                   Emisiones de N2O por RecursoComb
26          EmisionesCO2Eq                    Emisiones de CO2 Eq por Recurso
27       factorEmisionCO2e                Emisiones de CO2 Eq/kWh por Sistema
34            PerdidasEner                    Perdidas de Energía por Sistema
35           GeneSeguridad                Generación de Seguridad por Recurso
36         GeneFueraMerito             Generación Fuera de Mérito por Recurso
38            GeneProgDesp                  Generación Programada por Recurso
39          GeneProgRedesp       Generación Programada Redespacho por Recurso
40               DispoReal                    Disponibilidad Real por Recurso
41               DispoCome               Disponibilidad Comercial por Recurso
42          DispoDeclarada               Disponibilidad Declarada por Recurso
43             RecoPosEner        Reconciliación Positiva Energía por Recurso
44             RecoNegEner        Reconciliación Negativa Energía por Recurso
46                DesvEner                   Desviaciones Energía por Recurso
47              DesvMoneda                    Desviaciones Moneda por Recurso
48           RecoPosMoneda         Reconciliación Positiva Moneda por Recurso
49           RecoNegMoneda         Reconciliación Negativa Moneda por Recurso
55             RestSinAliv              Restricciones sin Alivios por Sistema
93            CostMargDesp     Costo Marginal Despacho Programado por Sistema
94              DesvMoneda                    Desviaciones Moneda por Sistema
107        PerdidasEnerReg                Perdidas de Energía Regulada Agente
108        PerdidasEnerReg               Perdidas de Energía Regulada Sistema
109      PerdidasEnerNoReg             Perdidas de Energía No Regulada Agente
110      PerdidasEnerNoReg            Perdidas de Energía No Regulada Sistema
111           PerdidasEner                         Perdidas de Energía Agente
112    DesvGenVariableDesp            Desviación generación variable despacho
114  DesvGenVariableRedesp          Desviación generación variable redespacho
117                 ENFICC  Energía en Firme Cargo por Confiabilidad - ENF...
118                 ENFICC  Energía en Firme Cargo por Confiabilidad - ENF...
119       CompNetArranPara        Compras Netas Arranque y Parada por Sistema
129            CapEfecNeta                Capacidad Efectiva Neta por Recurso
130                DemaSIN                    Demanda Energia SIN por Sistema
134         ObligEnerFirme   Obligación de Energía en Firme - OEF por Recurso
143          DDVContratada                         DDV Contratada por Recurso
145        ComContRespEner              Compras Contrato Respaldo por Recurso
146           PrecCargConf         Precio Cargo por Confiabilidad por Recurso
147       VentContRespEner               Ventas Contrato Respaldo por Recurso
161          PrecOferIdeal                 Precio de Oferta Ideal por Recurso
166         PPPrecBolsNaci        Precio Bolsa Nacional Ponderado por Sistema
168               IrrPanel                      Irradiación Panel por Recurso
169              IrrGlobal                     Irradiación Global por Recurso
170              TempPanel                      Temperatura Panel por Recurso
171           TempAmbSolar             Temperatura Ambiente Solar por Recurso

          Entity            Type MetricUnits
4        Sistema  HourlyEntities         kWh
5        Sistema  HourlyEntities         kWh
8        Recurso  HourlyEntities        MBTU
9    Combustible  HourlyEntities        MBTU
10       Recurso  HourlyEntities         kWh
11       Recurso  HourlyEntities           #
13       Recurso  HourlyEntities     COP/kWh
21       Recurso  HourlyEntities         kWh
22   RecursoComb  HourlyEntities        MBTU
23   RecursoComb  HourlyEntities      TonCO2
24   RecursoComb  HourlyEntities      TonCH4
25   RecursoComb  HourlyEntities      TonN2O
26       Recurso  HourlyEntities   gCO2e/kWh
27       Sistema  HourlyEntities   gCO2e/kWh
34       Sistema  HourlyEntities         kWh
35       Recurso  HourlyEntities         kWh
36       Recurso  HourlyEntities         kWh
38       Recurso  HourlyEntities         kWh
39       Recurso  HourlyEntities         kWh
40       Recurso  HourlyEntities          kW
41       Recurso  HourlyEntities          kW
42       Recurso  HourlyEntities         kWh
43       Recurso  HourlyEntities         kWh
44       Recurso  HourlyEntities         kWh
46       Recurso  HourlyEntities         kWh
47       Recurso  HourlyEntities         COP
48       Recurso  HourlyEntities         COP
49       Recurso  HourlyEntities         COP
55       Sistema  HourlyEntities         COP
93       Sistema  HourlyEntities     COP/kWh
94       Sistema  HourlyEntities         COP
107       Agente  HourlyEntities         kWh
108      Sistema  HourlyEntities         kWh
109       Agente  HourlyEntities         kWh
110      Sistema  HourlyEntities         kWh
111       Agente  HourlyEntities         kWh
112      Recurso  HourlyEntities         kWh
114      Recurso  HourlyEntities         kWh
117      Recurso   DailyEntities         kWh
118      Sistema   DailyEntities         kWh
119      Sistema   DailyEntities         COP
129      Recurso   DailyEntities          kW
130      Sistema   DailyEntities         kWh
134      Recurso   DailyEntities         kWh
143      Recurso   DailyEntities         kWh
145      Recurso   DailyEntities         COP
146      Recurso   DailyEntities     USD/kWh
147      Recurso   DailyEntities         COP
161      Recurso   DailyEntities     COP/kWh
166      Sistema   DailyEntities     COP/kWh
168      Recurso   DailyEntities        W/m2
169      Recurso   DailyEntities        W/m2
170      Recurso   DailyEntities
171      Recurso   DailyEntities          °C

In [17]:
# Celda 17 — Buscar si existe una metrica de generacion YA desglosada
# por tipo (hidraulica/termica) a nivel Sistema, antes de asumir que
# hay que construirla nosotros desde el detalle por recurso.
#
# Uso una expresion regular simple ([eé] y [aá]) para que el buscador
# encuentre el termino tanto con tilde como sin tilde, por si el catalogo
# no es consistente en su escritura.

mascara_termica = catalogo.apply(lambda columna: columna.astype(str).str.contains("t[eé]rmic", case=False, na=False, regex=True))
print("=== Resultados para 'termica/térmica' ===")
print(catalogo[mascara_termica.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

mascara_hidraulica = catalogo.apply(lambda columna: columna.astype(str).str.contains("hidr[aá]ulic", case=False, na=False, regex=True))
print("\n=== Resultados para 'hidraulica/hidráulica' ===")
print(catalogo[mascara_hidraulica.any(axis=1)][["MetricId", "MetricName", "Entity", "Type", "MetricUnits"]])

=== Resultados para 'termica/térmica' ===
                MetricId                                         MetricName  \
6           PrecBolsNaci                  Precio Bolsa Nacional por Sistema
8    ConsCombustibleMBTU               Consumo Combustible MBTU por Recurso
9    ConsCombustibleMBTU                           Consumo Combustible MBTU
22         ConsCombAprox  Consumo Combustible Aproximado para el Factor ...
130              DemaSIN                    Demanda Energia SIN por Sistema

          Entity            Type MetricUnits
6        Sistema  HourlyEntities     COP/kWh
8        Recurso  HourlyEntities        MBTU
9    Combustible  HourlyEntities        MBTU
22   RecursoComb  HourlyEntities        MBTU
130      Sistema   DailyEntities         kWh

=== Resultados para 'hidraulica/hidráulica' ===
             MetricId                       MetricName   Entity  \
130           DemaSIN  Demanda Energia SIN por Sistema  Sistema
150  VoluUtilDiarMasa  Volumen Útil diario por Embalse  Embalse

              Type MetricUnits
130  DailyEntities         kWh
150  DailyEntities          m3

In [18]:
# Celda 18 — Confirmar que DemaReal y Gene (Sistema) comparten la misma
# estructura horaria que el precio de bolsa, antes de generalizar la funcion.
import json
cuerpo_demanda = {"MetricId": "DemaReal", "StartDate": "2024-01-01", "EndDate": "2024-01-01", "Entity": "Sistema"}
resp_demanda = requests.post("https://servapibi.xm.com.co/hourly", json=cuerpo_demanda)
print("=== DemaReal ===")
print(json.dumps(resp_demanda.json()["Items"][0], indent=2, ensure_ascii=False)[:400])

cuerpo_generacion = {"MetricId": "Gene", "StartDate": "2024-01-01", "EndDate": "2024-01-01", "Entity": "Sistema"}
resp_generacion = requests.post("https://servapibi.xm.com.co/hourly", json=cuerpo_generacion)
print("\n=== Gene (Sistema) ===")
print(json.dumps(resp_generacion.json()["Items"][0], indent=2, ensure_ascii=False)[:400])

=== DemaReal ===
{
  "Date": "2024-01-01",
  "HourlyEntities": [
    {
      "Id": "Sistema",
      "Values": {
        "code": "Sistema",
        "Hour01": "7236893.31000",
        "Hour02": "7104164.61000",
        "Hour03": "7012446.40000",
        "Hour04": "6870115.23000",
        "Hour05": "6759771.97000",
        "Hour06": "6671795.60000",
        "Hour07": "6287595.26000",
        "Hour08": "6319646.62000"

=== Gene (Sistema) ===
{
  "Date": "2024-01-01",
  "HourlyEntities": [
    {
      "Id": "Sistema",
      "Values": {
        "code": "Sistema",
        "Hour01": "7343431.33000",
        "Hour02": "7211670.17000",
        "Hour03": "7120953.27000",
        "Hour04": "6979871.22000",
        "Hour05": "6874838.53000",
        "Hour06": "6719708.19000",
        "Hour07": "6353959.47000",
        "Hour08": "6413032.87000"

In [19]:
# Celda 19 — Funcion generica para descargar metricas HORARIAS (Sistema)
#
# DemaReal y Gene comparten la misma estructura de JSON que PrecBolsNaci
# (confirmado en la celda 18): HourlyEntities -> Values -> Hour01...Hour24.
# En vez de copiar descargar_precio_bolsa dos veces, la generalizamos para
# que reciba el MetricId y el nombre de columna como parametros.

def descargar_metrica_horaria(metric_id, fecha_inicio, fecha_fin, nombre_columna, entity="Sistema"):
    """
    Descarga una metrica HORARIA de la API de XM (endpoint /hourly).
    Maximo 31 dias por llamado.

    Parametros:
        metric_id: codigo de la metrica, ej. 'DemaReal' o 'Gene'
        fecha_inicio, fecha_fin: strings 'YYYY-MM-DD'
        nombre_columna: como se llamara la columna de valores en el DataFrame resultado
        entity: nivel de agregacion, 'Sistema' por defecto

    Devuelve:
        DataFrame de pandas en formato LARGO: columnas 'fecha_hora' y nombre_columna.
    """
    cuerpo_peticion = {
        "MetricId": metric_id,
        "StartDate": fecha_inicio,
        "EndDate": fecha_fin,
        "Entity": entity
    }

    respuesta = requests.post("https://servapibi.xm.com.co/hourly", json=cuerpo_peticion)
    respuesta.raise_for_status()
    datos = respuesta.json()

    filas = []
    for dia in datos["Items"]:
        fecha = dia["Date"]
        valores_del_dia = dia["HourlyEntities"][0]["Values"]
        for hora in range(1, 25):
            clave_hora = f"Hour{hora:02d}"
            valor = float(valores_del_dia[clave_hora])
            fecha_hora = pd.Timestamp(fecha) + pd.Timedelta(hours=hora - 1)
            filas.append({"fecha_hora": fecha_hora, nombre_columna: valor})

    return pd.DataFrame(filas)


def descargar_rango_horario_robusto(metric_id, fecha_inicio_total, fecha_fin_total, nombre_columna,
                                      dias_por_bloque=30, max_reintentos=3, entity="Sistema"):
    """Descarga una metrica horaria para un rango largo, en bloques, con reintentos."""
    fecha_actual = pd.Timestamp(fecha_inicio_total)
    fecha_limite = pd.Timestamp(fecha_fin_total)
    bloques_descargados = []
    bloques_fallidos = []
    numero_bloque = 1

    while fecha_actual <= fecha_limite:
        fin_de_bloque = min(fecha_actual + pd.Timedelta(days=dias_por_bloque - 1), fecha_limite)
        inicio_str = fecha_actual.strftime("%Y-%m-%d")
        fin_str = fin_de_bloque.strftime("%Y-%m-%d")

        exito = False
        for intento in range(1, max_reintentos + 1):
            try:
                df_bloque = descargar_metrica_horaria(metric_id, inicio_str, fin_str, nombre_columna, entity)
                bloques_descargados.append(df_bloque)
                print(f"[{metric_id}] Bloque {numero_bloque} OK: {inicio_str} a {fin_str} ({len(df_bloque)} filas)")
                exito = True
                break
            except Exception as error:
                print(f"  [{metric_id}] Bloque {numero_bloque} intento {intento} fallo: {error}")
                time.sleep(intento * 3)

        if not exito:
            bloques_fallidos.append((inicio_str, fin_str))
            print(f"  [{metric_id}] Bloque {numero_bloque} DESCARTADO tras {max_reintentos} intentos")

        fecha_actual = fin_de_bloque + pd.Timedelta(days=1)
        numero_bloque += 1
        time.sleep(1)

    if bloques_descargados:
        df_completo = pd.concat(bloques_descargados, ignore_index=True)
        df_completo = df_completo.sort_values("fecha_hora").drop_duplicates("fecha_hora").reset_index(drop=True)
    else:
        df_completo = pd.DataFrame()

    return df_completo, bloques_fallidos

print("Funciones genericas de descarga horaria listas")

Funciones genericas de descarga horaria listas

In [20]:
# Celda 20 — Mini-prueba: confirmar datos desde 2019 para demanda y generacion
df_test_dem = descargar_metrica_horaria("DemaReal", "2019-01-01", "2019-01-02", "demanda_kwh")
print("Demanda 2019 ->", df_test_dem.shape)
print(df_test_dem.head(3))

df_test_gen = descargar_metrica_horaria("Gene", "2019-01-01", "2019-01-02", "generacion_kwh")
print("\nGeneracion 2019 ->", df_test_gen.shape)
print(df_test_gen.head(3))

Demanda 2019 -> (48, 2)
           fecha_hora  demanda_kwh
0 2019-01-01 00:00:00   6276771.07
1 2019-01-01 01:00:00   6086853.43
2 2019-01-01 02:00:00   5896211.05

Generacion 2019 -> (48, 2)
           fecha_hora  generacion_kwh
0 2019-01-01 00:00:00      6235333.96
1 2019-01-01 01:00:00      6059405.81
2 2019-01-01 02:00:00      5870845.72

In [21]:
# Celda 21 — Descarga COMPLETA 2019-2025 de demanda y generacion, y guardado en disco

# --- Demanda real del sistema ---
df_demanda, fallos_demanda = descargar_rango_horario_robusto("DemaReal", "2019-01-01", "2025-12-31", "demanda_kwh")

print("\n===== RESUMEN DEMANDA =====")
print("Total de filas:", df_demanda.shape[0])
print("Rango de fechas:", df_demanda["fecha_hora"].min(), "a", df_demanda["fecha_hora"].max())
print("Bloques fallidos:", len(fallos_demanda))

df_demanda.to_csv("../data/demanda_real_2019_2025.csv", index=False)
print("Guardado en: ../data/demanda_real_2019_2025.csv")

# --- Generacion total del sistema ---
df_generacion, fallos_generacion = descargar_rango_horario_robusto("Gene", "2019-01-01", "2025-12-31", "generacion_kwh")

print("\n===== RESUMEN GENERACION =====")
print("Total de filas:", df_generacion.shape[0])
print("Rango de fechas:", df_generacion["fecha_hora"].min(), "a", df_generacion["fecha_hora"].max())
print("Bloques fallidos:", len(fallos_generacion))

df_generacion.to_csv("../data/generacion_total_2019_2025.csv", index=False)
print("Guardado en: ../data/generacion_total_2019_2025.csv")

[DemaReal] Bloque 1 OK: 2019-01-01 a 2019-01-30 (720 filas)
[DemaReal] Bloque 2 OK: 2019-01-31 a 2019-03-01 (720 filas)
[DemaReal] Bloque 3 OK: 2019-03-02 a 2019-03-31 (720 filas)
[DemaReal] Bloque 4 OK: 2019-04-01 a 2019-04-30 (720 filas)
[DemaReal] Bloque 5 OK: 2019-05-01 a 2019-05-30 (720 filas)
[DemaReal] Bloque 6 OK: 2019-05-31 a 2019-06-29 (720 filas)
[DemaReal] Bloque 7 OK: 2019-06-30 a 2019-07-29 (720 filas)
[DemaReal] Bloque 8 OK: 2019-07-30 a 2019-08-28 (720 filas)
[DemaReal] Bloque 9 OK: 2019-08-29 a 2019-09-27 (720 filas)
[DemaReal] Bloque 10 OK: 2019-09-28 a 2019-10-27 (720 filas)
[DemaReal] Bloque 11 OK: 2019-10-28 a 2019-11-26 (720 filas)
[DemaReal] Bloque 12 OK: 2019-11-27 a 2019-12-26 (720 filas)
[DemaReal] Bloque 13 OK: 2019-12-27 a 2020-01-25 (720 filas)
[DemaReal] Bloque 14 OK: 2020-01-26 a 2020-02-24 (720 filas)
[DemaReal] Bloque 15 OK: 2020-02-25 a 2020-03-25 (720 filas)
[DemaReal] Bloque 16 OK: 2020-03-26 a 2020-04-24 (720 filas)
[DemaReal] Bloque 17 OK: 2020-04-25 a 2020-05-24 (720 filas)
[DemaReal] Bloque 18 OK: 2020-05-25 a 2020-06-23 (720 filas)
[DemaReal] Bloque 19 OK: 2020-06-24 a 2020-07-23 (720 filas)
[DemaReal] Bloque 20 OK: 2020-07-24 a 2020-08-22 (720 filas)
[DemaReal] Bloque 21 OK: 2020-08-23 a 2020-09-21 (720 filas)
[DemaReal] Bloque 22 OK: 2020-09-22 a 2020-10-21 (720 filas)
[DemaReal] Bloque 23 OK: 2020-10-22 a 2020-11-20 (720 filas)
[DemaReal] Bloque 24 OK: 2020-11-21 a 2020-12-20 (720 filas)
[DemaReal] Bloque 25 OK: 2020-12-21 a 2021-01-19 (720 filas)
[DemaReal] Bloque 26 OK: 2021-01-20 a 2021-02-18 (720 filas)
[DemaReal] Bloque 27 OK: 2021-02-19 a 2021-03-20 (720 filas)
[DemaReal] Bloque 28 OK: 2021-03-21 a 2021-04-19 (720 filas)
[DemaReal] Bloque 29 OK: 2021-04-20 a 2021-05-19 (720 filas)
[DemaReal] Bloque 30 OK: 2021-05-20 a 2021-06-18 (720 filas)
[DemaReal] Bloque 31 OK: 2021-06-19 a 2021-07-18 (720 filas)
[DemaReal] Bloque 32 OK: 2021-07-19 a 2021-08-17 (720 filas)
[DemaReal] Bloque 33 OK: 2021-08-18 a 2021-09-16 (720 filas)
[DemaReal] Bloque 34 OK: 2021-09-17 a 2021-10-16 (720 filas)
[DemaReal] Bloque 35 OK: 2021-10-17 a 2021-11-15 (720 filas)
[DemaReal] Bloque 36 OK: 2021-11-16 a 2021-12-15 (720 filas)
[DemaReal] Bloque 37 OK: 2021-12-16 a 2022-01-14 (720 filas)
[DemaReal] Bloque 38 OK: 2022-01-15 a 2022-02-13 (720 filas)
[DemaReal] Bloque 39 OK: 2022-02-14 a 2022-03-15 (720 filas)
[DemaReal] Bloque 40 OK: 2022-03-16 a 2022-04-14 (720 filas)
[DemaReal] Bloque 41 OK: 2022-04-15 a 2022-05-14 (720 filas)
[DemaReal] Bloque 42 OK: 2022-05-15 a 2022-06-13 (720 filas)
[DemaReal] Bloque 43 OK: 2022-06-14 a 2022-07-13 (720 filas)
[DemaReal] Bloque 44 OK: 2022-07-14 a 2022-08-12 (720 filas)
[DemaReal] Bloque 45 OK: 2022-08-13 a 2022-09-11 (720 filas)
[DemaReal] Bloque 46 OK: 2022-09-12 a 2022-10-11 (720 filas)
[DemaReal] Bloque 47 OK: 2022-10-12 a 2022-11-10 (720 filas)
[DemaReal] Bloque 48 OK: 2022-11-11 a 2022-12-10 (720 filas)
[DemaReal] Bloque 49 OK: 2022-12-11 a 2023-01-09 (720 filas)
[DemaReal] Bloque 50 OK: 2023-01-10 a 2023-02-08 (720 filas)
[DemaReal] Bloque 51 OK: 2023-02-09 a 2023-03-10 (720 filas)
[DemaReal] Bloque 52 OK: 2023-03-11 a 2023-04-09 (720 filas)
[DemaReal] Bloque 53 OK: 2023-04-10 a 2023-05-09 (720 filas)
[DemaReal] Bloque 54 OK: 2023-05-10 a 2023-06-08 (720 filas)
[DemaReal] Bloque 55 OK: 2023-06-09 a 2023-07-08 (720 filas)
[DemaReal] Bloque 56 OK: 2023-07-09 a 2023-08-07 (720 filas)
[DemaReal] Bloque 57 OK: 2023-08-08 a 2023-09-06 (720 filas)
[DemaReal] Bloque 58 OK: 2023-09-07 a 2023-10-06 (720 filas)
[DemaReal] Bloque 59 OK: 2023-10-07 a 2023-11-05 (720 filas)
[DemaReal] Bloque 60 OK: 2023-11-06 a 2023-12-05 (720 filas)
[DemaReal] Bloque 61 OK: 2023-12-06 a 2024-01-04 (720 filas)
[DemaReal] Bloque 62 OK: 2024-01-05 a 2024-02-03 (720 filas)
[DemaReal] Bloque 63 OK: 2024-02-04 a 2024-03-04 (720 filas)
[DemaReal] Bloque 64 OK: 2024-03-05 a 2024-04-03 (720 filas)
[DemaReal] Bloque 65 OK: 2024-04-04 a 2024-05-03 (720 filas)
[DemaReal] Bloque 66 OK: 2024-05-04 a 2024-06-02 (720 filas)
[DemaReal] Bloque 67 OK: 2024-06-03 a 2024-07-02 (720 filas)
[DemaReal] Bloque 68 OK: 2024-07-03 a 2024-08-01 (720 filas)
[DemaReal] Bloque 69 OK: 2024-08-02 a 2024-08-31 (720 filas)
[DemaReal] Bloque 70 OK: 2024-09-01 a 2024-09-30 (720 filas)
[DemaReal] Bloque 71 OK: 2024-10-01 a 2024-10-30 (720 filas)
[DemaReal] Bloque 72 OK: 2024-10-31 a 2024-11-29 (720 filas)
[DemaReal] Bloque 73 OK: 2024-11-30 a 2024-12-29 (720 filas)
[DemaReal] Bloque 74 OK: 2024-12-30 a 2025-01-28 (720 filas)
[DemaReal] Bloque 75 OK: 2025-01-29 a 2025-02-27 (720 filas)
[DemaReal] Bloque 76 OK: 2025-02-28 a 2025-03-29 (720 filas)
[DemaReal] Bloque 77 OK: 2025-03-30 a 2025-04-28 (720 filas)
[DemaReal] Bloque 78 OK: 2025-04-29 a 2025-05-28 (720 filas)
[DemaReal] Bloque 79 OK: 2025-05-29 a 2025-06-27 (720 filas)
[DemaReal] Bloque 80 OK: 2025-06-28 a 2025-07-27 (720 filas)
[DemaReal] Bloque 81 OK: 2025-07-28 a 2025-08-26 (720 filas)
[DemaReal] Bloque 82 OK: 2025-08-27 a 2025-09-25 (720 filas)
[DemaReal] Bloque 83 OK: 2025-09-26 a 2025-10-25 (720 filas)
[DemaReal] Bloque 84 OK: 2025-10-26 a 2025-11-24 (720 filas)
[DemaReal] Bloque 85 OK: 2025-11-25 a 2025-12-24 (720 filas)
[DemaReal] Bloque 86 OK: 2025-12-25 a 2025-12-31 (168 filas)

===== RESUMEN DEMANDA =====
Total de filas: 61368
Rango de fechas: 2019-01-01 00:00:00 a 2025-12-31 23:00:00
Bloques fallidos: 0
Guardado en: ../data/demanda_real_2019_2025.csv
[Gene] Bloque 1 OK: 2019-01-01 a 2019-01-30 (720 filas)
[Gene] Bloque 2 OK: 2019-01-31 a 2019-03-01 (720 filas)
[Gene] Bloque 3 OK: 2019-03-02 a 2019-03-31 (720 filas)
[Gene] Bloque 4 OK: 2019-04-01 a 2019-04-30 (720 filas)
[Gene] Bloque 5 OK: 2019-05-01 a 2019-05-30 (720 filas)
[Gene] Bloque 6 OK: 2019-05-31 a 2019-06-29 (720 filas)
[Gene] Bloque 7 OK: 2019-06-30 a 2019-07-29 (720 filas)
[Gene] Bloque 8 OK: 2019-07-30 a 2019-08-28 (720 filas)
[Gene] Bloque 9 OK: 2019-08-29 a 2019-09-27 (720 filas)
[Gene] Bloque 10 OK: 2019-09-28 a 2019-10-27 (720 filas)
[Gene] Bloque 11 OK: 2019-10-28 a 2019-11-26 (720 filas)
[Gene] Bloque 12 OK: 2019-11-27 a 2019-12-26 (720 filas)
[Gene] Bloque 13 OK: 2019-12-27 a 2020-01-25 (720 filas)
[Gene] Bloque 14 OK: 2020-01-26 a 2020-02-24 (720 filas)
[Gene] Bloque 15 OK: 2020-02-25 a 2020-03-25 (720 filas)
[Gene] Bloque 16 OK: 2020-03-26 a 2020-04-24 (720 filas)
[Gene] Bloque 17 OK: 2020-04-25 a 2020-05-24 (720 filas)
[Gene] Bloque 18 OK: 2020-05-25 a 2020-06-23 (720 filas)
[Gene] Bloque 19 OK: 2020-06-24 a 2020-07-23 (720 filas)
[Gene] Bloque 20 OK: 2020-07-24 a 2020-08-22 (720 filas)
[Gene] Bloque 21 OK: 2020-08-23 a 2020-09-21 (720 filas)
[Gene] Bloque 22 OK: 2020-09-22 a 2020-10-21 (720 filas)
[Gene] Bloque 23 OK: 2020-10-22 a 2020-11-20 (720 filas)
[Gene] Bloque 24 OK: 2020-11-21 a 2020-12-20 (720 filas)
[Gene] Bloque 25 OK: 2020-12-21 a 2021-01-19 (720 filas)
[Gene] Bloque 26 OK: 2021-01-20 a 2021-02-18 (720 filas)
[Gene] Bloque 27 OK: 2021-02-19 a 2021-03-20 (720 filas)
[Gene] Bloque 28 OK: 2021-03-21 a 2021-04-19 (720 filas)
[Gene] Bloque 29 OK: 2021-04-20 a 2021-05-19 (720 filas)
[Gene] Bloque 30 OK: 2021-05-20 a 2021-06-18 (720 filas)
[Gene] Bloque 31 OK: 2021-06-19 a 2021-07-18 (720 filas)
[Gene] Bloque 32 OK: 2021-07-19 a 2021-08-17 (720 filas)
[Gene] Bloque 33 OK: 2021-08-18 a 2021-09-16 (720 filas)
[Gene] Bloque 34 OK: 2021-09-17 a 2021-10-16 (720 filas)
[Gene] Bloque 35 OK: 2021-10-17 a 2021-11-15 (720 filas)
[Gene] Bloque 36 OK: 2021-11-16 a 2021-12-15 (720 filas)
[Gene] Bloque 37 OK: 2021-12-16 a 2022-01-14 (720 filas)
[Gene] Bloque 38 OK: 2022-01-15 a 2022-02-13 (720 filas)
[Gene] Bloque 39 OK: 2022-02-14 a 2022-03-15 (720 filas)
[Gene] Bloque 40 OK: 2022-03-16 a 2022-04-14 (720 filas)
[Gene] Bloque 41 OK: 2022-04-15 a 2022-05-14 (720 filas)
[Gene] Bloque 42 OK: 2022-05-15 a 2022-06-13 (720 filas)
[Gene] Bloque 43 OK: 2022-06-14 a 2022-07-13 (720 filas)
[Gene] Bloque 44 OK: 2022-07-14 a 2022-08-12 (720 filas)
[Gene] Bloque 45 OK: 2022-08-13 a 2022-09-11 (720 filas)
[Gene] Bloque 46 OK: 2022-09-12 a 2022-10-11 (720 filas)
[Gene] Bloque 47 OK: 2022-10-12 a 2022-11-10 (720 filas)
[Gene] Bloque 48 OK: 2022-11-11 a 2022-12-10 (720 filas)
[Gene] Bloque 49 OK: 2022-12-11 a 2023-01-09 (720 filas)
[Gene] Bloque 50 OK: 2023-01-10 a 2023-02-08 (720 filas)
[Gene] Bloque 51 OK: 2023-02-09 a 2023-03-10 (720 filas)
[Gene] Bloque 52 OK: 2023-03-11 a 2023-04-09 (720 filas)
[Gene] Bloque 53 OK: 2023-04-10 a 2023-05-09 (720 filas)
[Gene] Bloque 54 OK: 2023-05-10 a 2023-06-08 (720 filas)
[Gene] Bloque 55 OK: 2023-06-09 a 2023-07-08 (720 filas)
[Gene] Bloque 56 OK: 2023-07-09 a 2023-08-07 (720 filas)
[Gene] Bloque 57 OK: 2023-08-08 a 2023-09-06 (720 filas)
[Gene] Bloque 58 OK: 2023-09-07 a 2023-10-06 (720 filas)
[Gene] Bloque 59 OK: 2023-10-07 a 2023-11-05 (720 filas)
[Gene] Bloque 60 OK: 2023-11-06 a 2023-12-05 (720 filas)
[Gene] Bloque 61 OK: 2023-12-06 a 2024-01-04 (720 filas)
[Gene] Bloque 62 OK: 2024-01-05 a 2024-02-03 (720 filas)
[Gene] Bloque 63 OK: 2024-02-04 a 2024-03-04 (720 filas)
[Gene] Bloque 64 OK: 2024-03-05 a 2024-04-03 (720 filas)
[Gene] Bloque 65 OK: 2024-04-04 a 2024-05-03 (720 filas)
[Gene] Bloque 66 OK: 2024-05-04 a 2024-06-02 (720 filas)
[Gene] Bloque 67 OK: 2024-06-03 a 2024-07-02 (720 filas)
[Gene] Bloque 68 OK: 2024-07-03 a 2024-08-01 (720 filas)
[Gene] Bloque 69 OK: 2024-08-02 a 2024-08-31 (720 filas)
[Gene] Bloque 70 OK: 2024-09-01 a 2024-09-30 (720 filas)
[Gene] Bloque 71 OK: 2024-10-01 a 2024-10-30 (720 filas)
[Gene] Bloque 72 OK: 2024-10-31 a 2024-11-29 (720 filas)
[Gene] Bloque 73 OK: 2024-11-30 a 2024-12-29 (720 filas)
[Gene] Bloque 74 OK: 2024-12-30 a 2025-01-28 (720 filas)
[Gene] Bloque 75 OK: 2025-01-29 a 2025-02-27 (720 filas)
[Gene] Bloque 76 OK: 2025-02-28 a 2025-03-29 (720 filas)
[Gene] Bloque 77 OK: 2025-03-30 a 2025-04-28 (720 filas)
[Gene] Bloque 78 OK: 2025-04-29 a 2025-05-28 (720 filas)
[Gene] Bloque 79 OK: 2025-05-29 a 2025-06-27 (720 filas)
[Gene] Bloque 80 OK: 2025-06-28 a 2025-07-27 (720 filas)
[Gene] Bloque 81 OK: 2025-07-28 a 2025-08-26 (720 filas)
[Gene] Bloque 82 OK: 2025-08-27 a 2025-09-25 (720 filas)
[Gene] Bloque 83 OK: 2025-09-26 a 2025-10-25 (720 filas)
[Gene] Bloque 84 OK: 2025-10-26 a 2025-11-24 (720 filas)
[Gene] Bloque 85 OK: 2025-11-25 a 2025-12-24 (720 filas)
[Gene] Bloque 86 OK: 2025-12-25 a 2025-12-31 (168 filas)

===== RESUMEN GENERACION =====
Total de filas: 61368
Rango de fechas: 2019-01-01 00:00:00 a 2025-12-31 23:00:00
Bloques fallidos: 0
Guardado en: ../data/generacion_total_2019_2025.csv